version: '3'
services:
  warehouse:
    build:
      dockerfile: Dockerfile
      context: .

    restart: always
    environment:
      DB_ENGINE: mysql
      MYSQL_DATABASE: vswarehouse
      MYSQL_USER: vswarehouse
      MYSQL_PASSWORD: dfksjdfsdkfjhweu
      MYSQL_HOST: db

    ports:
      - 8000:8000

  db:
    image: mysql

    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: asdlkjfhsdfkjhdf
      MYSQL_DATABASE: vswarehouse
      MYSQL_USER: vswarehouse
      MYSQL_PASSWORD: dfksjdfsdkfjhweu