# Generated by Django 2.2 on 2019-04-16 08:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_project_dependencies'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['identifier']},
        ),
        migrations.AlterModelOptions(
            name='release',
            options={'ordering': ['pypa_version', 'release_version']},
        ),
        migrations.RenameField(
            model_name='distribution',
            old_name='pypa_platform_string',
            new_name='platform',
        ),
        migrations.RemoveField(
            model_name='distribution',
            name='file',
        ),
        migrations.AddField(
            model_name='distribution',
            name='url',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='doom9',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='github',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='release',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
