# Generated by Django 2.2 on 2019-04-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_remove_release_release_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='published',
            field=models.DateTimeField(null=True),
        ),
    ]
