# Generated by Django 2.2 on 2019-05-05 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_auto_20190416_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='using_pip',
            field=models.BooleanField(default=False),
        ),
    ]
