# Generated by Django 2.2 on 2019-05-05 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_project_using_pip'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='from_vsutil',
            field=models.BooleanField(default=True),
        ),
    ]
